### PR TITLE
Bug/save webview state retain history

### LINKED ISSUE #48: App looses state when external link is open or when its sent to background
**Describe the bug**

When sharing an article or opening a medium link from an article, the app will either open an in-app browser or an installed app related to the link being opened when you return to the app, you're presented with the splash screen and the home page loads

**To Reproduce**

1. Go to article 
2. If the article has a link to external resource, click on it.
3. If it doesn't, click the 3 dots and share to any

**Expected behavior**

The app should bring you pack to the page you were browsing before you were redirected.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 5
 - OS: Android
 - Version: Pie

**Additional context**

### PR DESCRIPTION
**Pull request by sduduzog**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Documentation Update

## Description
This PR has work that enables the webview to [save](https://developer.android.com/reference/android/webkit/WebView.html#saveState(android.os.Bundle)) it's state when the app is sent to the background and [restores](https://developer.android.com/reference/android/webkit/WebView.html#restoreState(android.os.Bundle)) it when brought back to the foreground. Should there be no state, the app will load the base url as defaulted.

## Related Tickets & Documents
This PR resolves #48 
## [optional] What gif best describes this PR or how it makes you feel?
The great gatsby dude raising a glass

### CODE REVIEW

File: app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt [hunk 1]
```diff
@@ -23,10 +23,15 @@ class MainActivity : BaseActivity<ActivityMainBinding>(), CustomWebChromeClient.
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         setWebViewSettings()
-        navigateToHome()
+        savedInstanceState?.let { restoreState(it) }?: navigateToHome()
```
Comment (VarunBarad) [inline app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt]: Nitpicking
Edit spacing around `?:` for consistency. Making it like:
`savedInstanceState?.let { restoreState(it) } ?: navigateToHome()`

Comment (sduduzog) [reply app/src/main/java/to/dev/dev_android/view/main/view/MainActivity.kt]: Thanks for the heads up, on it
